{application,elreactordelamuerte,
             [{applications,[kernel,stdlib,elixir,logger,plug,cowboy,poison]},
              {description,"elreactordelamuerte"},
              {modules,['Elixir.Elreactordelamuerte','Elixir.PlugEx.Router',
                        'Elixir.Ticker']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Elreactordelamuerte',[]}},
              {env,[{cowboy_port,7000}]}]}.
